package com.sw.pojo;

/**
 * Contactinfo generated by MyEclipse - Hibernate Tools
 */

public class Contactinfo implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private User user;

	private int contactid;

	// Constructors

	/** default constructor */
	public Contactinfo() {
	}

	// Property accessors

	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public int getContactid() {
		return contactid;
	}

	public void setContactid(int contactid) {
		this.contactid = contactid;
	}

	
}